"""Stage 4 — incident brief generation and Slack posting.

Synthesize the deterministic findings into a human brief. Claude writes it when a
key is configured; otherwise a deterministic template produces an equivalent
brief so the pipeline always posts *something* useful offline.
"""

from __future__ import annotations

from sentinel.adapters.base import SlackAdapter
from sentinel.config import get_settings
from sentinel.llm import LLMClient, get_llm
from sentinel.llm.prompts import BRIEF_SYSTEM, build_brief_prompt
from sentinel.models import Incident, IncidentBrief

_DEFAULT_CHANNEL = "#incidents"


def _headline(incident: Incident) -> str:
    sev = incident.impact.severity.value if incident.impact else "SEV?"
    return f"[{sev}] {incident.alert.title}"


def _fallback_brief(incident: Incident) -> IncidentBrief:
    """Deterministic brief used when the LLM is unavailable."""
    a = incident.alert
    lines = [f"*{_headline(incident)}*", ""]

    if incident.impact:
        i = incident.impact
        lines.append(
            f":chart_with_upwards_trend: *Impact*: {i.error_rate:.1%} error rate "
            f"(baseline {i.baseline_error_rate:.1%}), ~{i.affected_users:,} users affected, "
            f"{i.requests_per_min:,.0f} req/min on `{a.service}`."
        )

    if incident.top_suspect:
        s = incident.top_suspect
        cause = (
            f":mag: *Likely cause* ({s.score:.0%} confidence): `{s.commit.short_sha}` "
            f"— {s.commit.message} (by {s.commit.author})."
        )
        if s.deploy:
            cause += f" Shipped by deploy `{s.deploy.id}`."
        lines.append(cause)
        if s.reasons:
            lines.append("   ↳ " + "; ".join(s.reasons))

    if incident.runbook_match:
        r = incident.runbook_match.runbook
        lines.append(f":book: *Runbook*: {r.title} (`{r.id}`) — {r.summary}")

    lines.append("")
    lines.append(":robot_face: _Auto-generated by Sentinel._")

    return IncidentBrief(
        headline=_headline(incident),
        body="\n".join(lines),
        generated_by="fallback",
    )


def generate_brief(incident: Incident, llm: LLMClient | None = None) -> IncidentBrief:
    """Produce the incident brief (LLM if available, else template)."""
    llm = llm or get_llm()
    text = llm.complete(BRIEF_SYSTEM, build_brief_prompt(incident), max_tokens=512)
    if text:
        return IncidentBrief(headline=_headline(incident), body=text, generated_by="llm")
    return _fallback_brief(incident)


def post_brief(
    incident: Incident,
    slack: SlackAdapter,
    llm: LLMClient | None = None,
    channel: str | None = None,
) -> IncidentBrief:
    """Generate the brief, post it to Slack, and record it on the incident."""
    brief = generate_brief(incident, llm)
    target = channel or get_settings().slack_channel or _DEFAULT_CHANNEL
    ts = slack.post_message(target, brief.body)
    incident.brief = brief
    incident.slack_ts = ts
    incident.add_event("briefed", f"Posted {brief.generated_by} brief to {target}")
    return brief
