"""Stage 5 — postmortem generation (on resolution).

Assemble a blameless postmortem from everything the incident accumulated. Claude
writes the prose when a key is present; otherwise a deterministic Markdown
template produces an equivalent report so resolution always yields a document.
"""

from __future__ import annotations

from sentinel.llm import LLMClient, get_llm
from sentinel.llm.prompts import POSTMORTEM_SYSTEM, build_postmortem_prompt
from sentinel.models import Incident, Postmortem


def _duration_str(incident: Incident) -> str:
    if not incident.resolved_at:
        return "unresolved"
    delta = incident.resolved_at - incident.created_at
    minutes = int(delta.total_seconds() // 60)
    return f"{minutes} min"


def _fallback_postmortem(incident: Incident) -> Postmortem:
    a = incident.alert
    sev = incident.impact.severity.value if incident.impact else "SEV?"
    title = f"Postmortem: {a.title} ({sev})"

    lines = [f"# {title}", ""]

    # Summary
    lines += ["## Summary", ""]
    summary = (
        f"A {sev} incident on `{a.service}` was detected via {a.source} at "
        f"{incident.created_at.isoformat()} and resolved after {_duration_str(incident)}."
    )
    lines += [summary, ""]

    # Impact
    lines += ["## Impact", ""]
    if incident.impact:
        i = incident.impact
        lines += [
            f"- **Severity**: {i.severity.value}",
            f"- **Error rate**: {i.error_rate:.1%} (baseline {i.baseline_error_rate:.1%})",
            f"- **Affected users**: ~{i.affected_users:,}",
            f"- **Throughput**: {i.requests_per_min:,.0f} req/min",
            "",
        ]
    else:
        lines += ["- Impact was not quantified.", ""]

    # Root cause
    lines += ["## Root Cause", ""]
    if incident.top_suspect:
        s = incident.top_suspect
        lines.append(
            f"The most likely cause is commit `{s.commit.short_sha}` "
            f"(\"{s.commit.message}\", by {s.commit.author}), confidence {s.score:.0%}."
        )
        if s.deploy:
            lines.append(
                f"It was shipped by deploy `{s.deploy.id}` to "
                f"{s.deploy.environment} at {s.deploy.deployed_at.isoformat()}."
            )
        if s.reasons:
            lines += ["", "Signals:"] + [f"- {r}" for r in s.reasons]
    else:
        lines.append("No likely root-cause commit was identified.")
    lines.append("")

    # Timeline
    lines += ["## Timeline", ""]
    for e in incident.timeline:
        detail = f" — {e.detail}" if e.detail else ""
        lines.append(f"- `{e.at.isoformat()}` **{e.label}**{detail}")
    lines.append("")

    # Action items
    lines += ["## Action Items", ""]
    if incident.runbook_match:
        lines.append(
            f"- Follow runbook **{incident.runbook_match.runbook.title}** "
            f"(`{incident.runbook_match.runbook.id}`) for remediation and prevention."
        )
    if incident.top_suspect and incident.top_suspect.deploy:
        lines.append(
            f"- Review commit `{incident.top_suspect.commit.short_sha}` and add a "
            f"regression test for the failure mode it introduced."
        )
    lines.append("- Add/verify an alert to catch recurrence earlier.")
    lines.append("")
    lines.append("_Auto-generated by Sentinel._")

    return Postmortem(title=title, body="\n".join(lines), generated_by="fallback")


def generate_postmortem(incident: Incident, llm: LLMClient | None = None) -> Postmortem:
    """Produce the postmortem (LLM if available, else template) and record it."""
    llm = llm or get_llm()
    sev = incident.impact.severity.value if incident.impact else "SEV?"
    title = f"Postmortem: {incident.alert.title} ({sev})"

    text = llm.complete(POSTMORTEM_SYSTEM, build_postmortem_prompt(incident), max_tokens=1500)
    postmortem = (
        Postmortem(title=title, body=text, generated_by="llm")
        if text
        else _fallback_postmortem(incident)
    )
    incident.postmortem = postmortem
    incident.add_event("postmortem", f"Generated {postmortem.generated_by} postmortem")
    return postmortem
